name: GitHub Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: readme-updates
  cancel-in-progress: true

jobs:
  activity-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Activity Graph
        uses: ashutosh00710/github-readme-activity-graph-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: github-dark
