name: GitHub Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: activity-graph
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          max_commits: 100
          theme: github-dark
          hide_border: true
          area: true
